export const data = [  
    {  
      id: 0,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,
    },  
    {  
      id: 1,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10, 
    },  
    {  
      id: 2,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,
    },  
    {  
      id: 3,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,  
    },  
    {  
      id: 4,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10, 
    },  
    {  
      id: 5,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,  
    },  
    {  
      id: 6,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10, 
    },  
    {  
      id: 7,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,  
    },  
    {  
      id: 8,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10, 
    },  
    {  
      id: 9,  
      date: "Canada",  
      description: "Bill",  
      invoice: "G004124521",  
      amount: 10,  
    }  
  ];